# Portfolio Analytics Configuration
# Generated: 2025-06-26

portfolio_analysis:
  risk_free_rates:
    sol_staking: 0.04      # 4% APR SOL staking
    usdc_staking: 0.05     # 5% APR USDC staking
  cost_allocation_method: "daily_flat"
  analysis_periods: [1, 7, 30, 90]  # days
  min_position_threshold: 0.01       # SOL minimum for analysis

infrastructure_costs:
  monthly:
    vps_cost: 8.54         # USD
    rpc_endpoints: 20.0   # USD  
    bot_subscription: 00.0 # USD
    # Total: 28.54 USD/month = 0.95 USD/day

currency_analysis:
  primary_denomination: "sol"
  include_usdc_view: true
  sol_price_source: "moralis"

visualization:
  chart_types: ["equity_curve", "drawdown", "cost_impact", "strategy_heatmap"]
  timestamp_format: "%Y%m%d_%H%M"
  filters:
    min_strategy_occurrences: 2  # minimum positions per strategy
    top_strategies_only: 10      # show only top N strategies
    exclude_outliers: false       # remove statistical outliers
    date_range_filter: false      # custom date range selection

# Weekend Parameter Analysis Configuration
weekend_analysis:
  weekend_size_reduction: 0        # 0=disabled, 1=enabled for all positions
  size_reduction_percentage: 80    # 80% reduction = 20% remains; 0 = no analysis
  
  # Analysis notes:
  # - CSV always represents actual positions (regardless of weekend_size_reduction setting)
  # - weekend_size_reduction=1: CSV has reduced positions, simulate enlarged for comparison
  # - weekend_size_reduction=0: CSV has normal positions, simulate reduced for comparison
  # - Only positions opened during weekend (Sat/Sun UTC) are affected by simulation
  # - Weekday positions remain identical in both scenarios
  # - Weekend classification based on open_timestamp, not duration

# Data Source Configuration for Offline-First Analysis
data_source:
  prefer_offline_cache: true      # true = offline first, false = online first
  interactive_gap_handling: true  # true = ask user, false = auto fallback
  auto_generate_offline: false    # true = bulk generate, false = on-demand

api_settings:
  # set 'true' to turn off all the API queries and use only /price_cache/ files.
  # set 'false'to turn on API queries.
  cache_only: false

# TP/SL Analysis Configuration
tp_sl_analysis:
  enable_custom_params: false          # Master switch for custom parameters
  
  # Time horizon controls (for Phase 3B)
  post_close_multiplier: 1.0           # 1x = position duration length
  min_post_close_hours: 2              # Minimum post-close analysis period
  max_post_close_hours: 48             # Maximum 2 days
  
  # Analysis scope filters
  scope_filters:
    enable_date_filter: false
    analysis_date_from: null           # Optional "YYYY-MM-DD" start date
    last_n_days: null                  # Alternative: analyze last N days only
    
    # Position quality filters
    min_position_duration_hours: 1     # Skip very short positions
    min_position_value_sol: 0.1        # Skip tiny positions  
    exclude_active_positions: true     # Skip active_at_log_end positions
    
    # Close reason filters
    include_close_reasons: ["TP", "SL", "LV", "OOR", "other"]
    
  # Peak PnL extraction settings
  significance_threshold: 0.01          # Minimum absolute % to consider significant
  min_samples_for_confidence: 5        # Minimum PnL readings for high confidence
  
# PHASE 3B: Post-close analysis settings
  post_close_analysis:
    enable_post_close: true               # Master switch for Phase 3B
    
    # Data coverage requirements
    min_data_coverage_pct: 80             # Minimum % of expected data points
    max_gap_hours: 6                      # Skip analysis if gaps > 6 hours
    
    # LP position valuation method
    lp_valuation_method: "simplified_il"  # "simplified_il" vs "accurate_concentrated" 
    fee_allocation_method: "volume_proportional"  # Algorithm for fee simulation
    
    # Analysis quality controls
    min_post_close_samples: 12            # Minimum price points for analysis
    confidence_threshold: "medium"        # "low"/"medium"/"high" required confidence
    
  # Performance and memory settings
  performance:
    batch_size: 50                        # Positions per batch
    max_parallel_fetches: 3               # Concurrent API calls
    enable_progress_logging: true         # Show progress during bulk analysis

  # PHASE 4: TP/SL Range Testing Configuration
range_testing:
  enable: true  # Master switch to run this analysis

  # Define TP levels to test (in percentage)
  tp_levels: [2, 6, 12] 

  # Define SL levels to test (in percentage, positive value)
  sl_levels: [3, 6, 9, 15]

  # Metric for heatmap color and ranking
  primary_ranking_metric: "total_pnl"

  # PHASE 5: TP/SL Optimization Engine
optimization_engine:
  enable: true
  min_positions_for_optimization: 1 # Min positions for a strategy to be analyzed

  # Time decay settings for weighting recent performance
  time_weighting:
    enable: true
    last_n_days_full_weight: 7
    decay_period_weeks: 4
    minimum_weight: 0.5